#!/usr/bin/env python3
"""
主要作用:
- 维护项目唯一的接口注册表和分组定义
- 同时服务 `update_daily.py` 的更新调度和 `auto_fill_data.py` 的补齐调度
"""

from copy import deepcopy

DEFAULT_BY_DATE_PAGE_LIMIT = 5000
DEFAULT_BY_DATE_MAX_PAGES = 3
DEFAULT_HEALTH_RECENT_TRADE_DAYS = 90
BY_STOCK_RUNTIME_CONFIG = {
    "resume_code_state": True,
    "api_process_timeout_sec": 20,
    "progress_log_interval": 50,
    "active_code_log_interval": 0,
    "live_progress_include_code": False,
}

BY_STOCK_BATCH_STOCK_POOL_CONFIG = {
    "batch_stock_pool_request": True,
    "batch_split_on_error": True,
    "batch_per_trade_date_request": True,
}


INTERFACE_CONFIG = {
    "daily": {
        "type": "standalone",
        "func": "update_daily",
        "group": "core",
        "path": "daily",
        "prefix": "daily_",
        "date_col": "trade_date",
        "root": "stock",
        "use_pagination": True,
        "page_limit": 6000,
        "max_pages": 4,
        "parallel_writers": 8,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "daily_basic": {
        "type": "standalone",
        "func": "update_daily_basic",
        "group": "core",
        "path": "daily_basic",
        "prefix": "daily_basic_",
        "date_col": "trade_date",
        "root": "stock",
        "use_pagination": True,
        "page_limit": 6000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "required_columns": ["close", "turnover_rate", "pb", "total_mv"],
        "nullable_columns": ["pb", "pe", "pe_ttm", "ps", "ps_ttm", "dv_ratio", "dv_ttm", "volume_ratio"],
        "enable_dividend_backfill_recheck": True,
        "dividend_backfill_max_codes": 300,
    },
    "moneyflow": {
        "type": "standalone",
        "func": "update_moneyflow",
        "group": "core",
        "path": "moneyflow_data/individual/tushare",
        "prefix": "moneyflow_",
        "force_by_date": True,
        "save_granularity": "year_date",
        "date_col": "trade_date",
        "root": "stock",
        "use_pagination": True,
        "page_limit": 6000,
        "max_pages": 3,
        "required_columns": ["buy_sm_vol", "sell_sm_vol", "net_mf_vol"],
    },
    "trade_cal": {
        "type": "standalone",
        "func": "update_trade_cal",
        "group": "core",
        "path": "trade_cal",
        "prefix": "trade_cal_",
        "fixed_file_name": "trade_cal_all.csv",
        "root": "stock",
        "required_columns": ["exchange", "cal_date", "is_open"],
    },
    "stk_nineturn": {
        "type": "by_date",
        "api": "stk_nineturn",
        "path": "stk_nineturn",
        "prefix": "stk_nineturn_",
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "limit_step": {
        "type": "by_date",
        "api": "limit_step",
        "path": "limit_step",
        "prefix": "limit_step_",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["name", "nums"],
    },
    "limit_cpt_list": {
        "type": "by_date",
        "api": "limit_cpt_list",
        "path": "limit_cpt_list",
        "prefix": "limit_cpt_list_",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["net_buy"],
    },
    "limit_list_d": {
        "type": "by_date",
        "api": "limit_list_d",
        "path": "limit_list_d",
        "prefix": "limit_list_d_",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": 2500,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["close", "pct_chg", "amount", "turnover_ratio"],
    },
    "limit_list_ths": {
        "type": "by_date",
        "api": "limit_list_ths",
        "path": "limit_list_ths",
        "prefix": "limit_list_ths_",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": 4000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["close", "pct_chg", "fd_amount", "strth"],
    },
    "top_list": {
        "type": "by_date",
        "api": "top_list",
        "path": "top_list",
        "prefix": "top_list_",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": 10000,
        "max_pages": 3,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["close", "pct_change", "amount", "net_amount"],
        "dedup_cols": ["trade_date", "ts_code"],
        "min_rows_per_date": 10,
    },
    "top_inst": {
        "type": "by_date",
        "api": "top_inst",
        "path": "top_inst",
        "prefix": "top_inst_",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": 10000,
        "max_pages": 3,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["buy", "sell", "net_buy"],
        "dedup_cols": ["trade_date", "ts_code"],
        "min_rows_per_date": 10,
    },
    "stk_auction_o": {
        "type": "by_date",
        "api": "stk_auction_o",
        "path": "stk_auction_o",
        "prefix": "stk_auction_o_",
        "save_granularity": "year_stock",
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "auction",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["price", "vol", "amount"],
    },
    "stk_auction_c": {
        "type": "by_date",
        "api": "stk_auction_c",
        "path": "stk_auction_c",
        "prefix": "stk_auction_c_",
        "save_granularity": "year_stock",
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "auction",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["price", "vol", "amount"],
    },
    "kpl_list": {
        "type": "by_date",
        "api": "kpl_list",
        "path": "theme_data/kpl_list",
        "prefix": "",
        "force_by_date": True,
        "partition_by_year_dir": True,
        "use_pagination": False,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["pct_chg", "amount", "turnover_rate", "status"],
        "expected_empty_ok": True,
        "max_trailing_gap_trade_days": 3,
        "whitelist_on_date_gap_only": True,
    },
    "dc_concept": {
        "type": "standalone",
        "func": "update_dc_concept",
        "group": "theme",
        "path": "theme_data/dc_concept",
        "prefix": "",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["name", "pct_change", "strength", "hot"],
        "save_granularity": "year_month",
    },
    "kpl_concept_cons": {
        "type": "standalone",
        "func": "update_kpl_concept_cons",
        "group": "theme",
        "path": "theme_data/kpl_concept_cons",
        "prefix": "",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["name", "con_name", "con_code", "hot_num"],
        "save_granularity": "year_month",
    },
    "dc_concept_cons": {
        "type": "standalone",
        "func": "update_dc_concept_cons",
        "group": "theme",
        "path": "theme_data/dc_concept_cons",
        "prefix": "",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["name", "theme_code", "trade_date"],
        "save_granularity": "year_month",
    },
    "ths_index": {
        "type": "standalone",
        "func": "update_ths_index",
        "group": "theme",
        "api": "ths_index",
        "path": "theme_data/ths_index",
        "prefix": "ths_index_",
        "root": "stock",
        "fixed_file_name": "ths_index_all.csv",
        "calendar_aligned": False,
        "latest_trade_days_override": 1,
        "required_columns": ["ts_code", "name", "count", "exchange", "list_date", "type"],
    },
    "ths_member": {
        "type": "standalone",
        "func": "update_ths_member",
        "group": "theme",
        "path": "theme_data/ths_member",
        "prefix": "",
        "date_col": "in_date",
        "dedup_cols": ["ts_code", "con_code"],
        "root": "stock",
        "calendar_aligned": False,
        "latest_trade_days_override": 1,
        "full_trade_days_override": 1,
        "required_columns": ["ts_code", "con_code", "con_name"],
    },
    "ths_daily": {
        "type": "standalone",
        "func": "update_ths_daily",
        "group": "theme",
        "path": "theme_data/ths_daily",
        "prefix": "ths_daily_",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["ts_code", "trade_date"],
        "calendar_aligned": True,
        "page_limit": 3000,
        "row_truncation_guard": 3000,
    },
    "dc_daily": {
        "type": "standalone",
        "func": "update_dc_daily",
        "group": "theme",
        "path": "theme_data/dc_daily",
        "prefix": "dc_daily_",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["close", "open", "high", "low", "pct_change", "vol", "amount"],
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
    },
    "dc_index": {
        "type": "standalone",
        "func": "update_dc_index",
        "group": "theme",
        "path": "theme_data/dc_index",
        "prefix": "dc_index_",
        "fixed_file_name": "dc_index_all.csv",
        "date_col": "trade_date",
        "root": "stock",
        "latest_trade_days_override": 1,
        "required_columns": ["ts_code", "name", "trade_date"],
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
    },
    "dc_member": {
        "type": "standalone",
        "func": "update_dc_member",
        "group": "theme",
        "path": "theme_data/dc_member",
        "prefix": "",
        "date_col": "trade_date",
        "dedup_cols": ["ts_code", "con_code", "trade_date"],
        "root": "stock",
        "latest_trade_days_override": 1,
        "full_trade_days_override": 1,
        "page_limit": 5000,
        "max_pages": 20,
        "per_code_sleep_sec": 1.0,
        "rate_limit_retry_sleep_sec": 3.0,
        "max_per_code_retries": 4,
        "required_columns": ["ts_code", "con_code", "trade_date"],
    },
    "hm_detail": {
        "type": "by_date",
        "api": "hm_detail",
        "path": "hm_detail",
        "prefix": "hm_detail_",
        "force_by_date": True,
        "save_granularity": "year_date",
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["buy_amount", "sell_amount", "net_amount", "hm_name"],
    },
    "hm_list": {
        "type": "by_date",
        "api": "hm_list",
        "path": "hm_list",
        "prefix": "hm_list_",
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
        "fixed_file_name": "hm_list.csv",
        "partition_by_year_dir": False,
        "health_recent_trade_days": 90,
        "group": "limit",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["ts_code", "net_amount"],
        "default_whitelist": True,
    },
    "moneyflow_ths": {
        "type": "by_date",
        "api": "moneyflow_ths",
        "path": "moneyflow_data/individual/ths",
        "prefix": "moneyflow_ths_",
        "force_by_date": True,
        "save_granularity": "year_date",
        "use_pagination": True,
        "page_limit": DEFAULT_BY_DATE_PAGE_LIMIT,
        "max_pages": DEFAULT_BY_DATE_MAX_PAGES,
        "health_recent_trade_days": DEFAULT_HEALTH_RECENT_TRADE_DAYS,
        "group": "moneyflow",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["net_amount"],
    },
    "moneyflow_hsgt": {
        "type": "by_date",
        "api": "moneyflow_hsgt",
        "path": "moneyflow_data/market/hsgt",
        "prefix": "moneyflow_hsgt_",
        "use_pagination": True,
        "page_limit": DEFAULT_BY_DATE_PAGE_LIMIT,
        "max_pages": DEFAULT_BY_DATE_MAX_PAGES,
        "health_recent_trade_days": DEFAULT_HEALTH_RECENT_TRADE_DAYS,
        "group": "moneyflow",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["hgt", "sgt", "north_money", "south_money"],
    },
    "moneyflow_ind_ths": {
        "type": "by_date",
        "api": "moneyflow_ind_ths",
        "path": "moneyflow_data/sector/ths_industry",
        "prefix": "moneyflow_ind_ths_",
        "use_pagination": True,
        "page_limit": DEFAULT_BY_DATE_PAGE_LIMIT,
        "max_pages": DEFAULT_BY_DATE_MAX_PAGES,
        "health_recent_trade_days": DEFAULT_HEALTH_RECENT_TRADE_DAYS,
        "group": "moneyflow",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["industry", "close", "net_buy_amount", "net_sell_amount", "net_amount"],
    },
    "moneyflow_cnt_ths": {
        "type": "by_date",
        "api": "moneyflow_cnt_ths",
        "path": "moneyflow_data/sector/ths_concept",
        "prefix": "moneyflow_concept_ths_",
        "use_pagination": True,
        "page_limit": DEFAULT_BY_DATE_PAGE_LIMIT,
        "max_pages": DEFAULT_BY_DATE_MAX_PAGES,
        "health_recent_trade_days": DEFAULT_HEALTH_RECENT_TRADE_DAYS,
        "group": "moneyflow",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["name", "close_price", "net_buy_amount", "net_sell_amount", "net_amount"],
    },
    "moneyflow_mkt_dc": {
        "type": "by_date",
        "api": "moneyflow_mkt_dc",
        "path": "moneyflow_data/market/dc_market",
        "prefix": "moneyflow_dc_market_",
        "use_pagination": True,
        "page_limit": DEFAULT_BY_DATE_PAGE_LIMIT,
        "max_pages": DEFAULT_BY_DATE_MAX_PAGES,
        "health_recent_trade_days": DEFAULT_HEALTH_RECENT_TRADE_DAYS,
        "group": "moneyflow",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["close_sh", "close_sz", "net_amount", "buy_elg_amount"],
    },
    "repurchase": {
        "type": "by_date",
        "api": "repurchase",
        "path": "repurchase",
        "prefix": "",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": DEFAULT_BY_DATE_PAGE_LIMIT,
        "max_pages": DEFAULT_BY_DATE_MAX_PAGES,
        "partition_by_year_dir": True,
        "save_granularity": "year",
        "health_recent_trade_days": DEFAULT_HEALTH_RECENT_TRADE_DAYS,
        "group": "repurchase",
        "date_col": "ann_date",
        "root": "stock",
        "required_columns": ["proc", "vol", "amount"],
        "expected_empty_ok": True,
        "retention_days": 1095,
    },
    "income": {
        "type": "by_stock",
        "api": "income",
        "path": "income",
        "prefix": "income_",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        **BY_STOCK_RUNTIME_CONFIG,
        "batch_per_trade_date_request": False,
        "batch_initial_code_chunk_size": 1000,
    },
    "balancesheet": {
        "type": "by_stock",
        "api": "balancesheet",
        "path": "balancesheet",
        "prefix": "balancesheet_",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        **BY_STOCK_RUNTIME_CONFIG,
        "batch_per_trade_date_request": False,
        "batch_initial_code_chunk_size": 1000,
    },
    "cashflow": {
        "type": "by_stock",
        "api": "cashflow",
        "path": "cashflow",
        "prefix": "cashflow_",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        **BY_STOCK_RUNTIME_CONFIG,
        "batch_per_trade_date_request": False,
        "batch_initial_code_chunk_size": 1000,
    },
    "forecast": {
        "type": "by_date",
        "api": "forecast",
        "path": "forecast",
        "prefix": "forecast_",
        "force_by_date": True,
        "use_pagination": False,
        "use_date_range_fetch": True,
        "date_fetch_with_stock_pool": True,
        "code_param": "ts_code",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        "expected_empty_ok": True,
    },
    "express": {
        "type": "by_stock",
        "api": "express_vip",
        "path": "express",
        "prefix": "express_",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        "calendar_aligned": False,
        "health_recent_trade_days": 180,
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        **BY_STOCK_RUNTIME_CONFIG,
        "batch_per_trade_date_request": False,
        "batch_initial_code_chunk_size": 1000,
    },
    "fina_indicator": {
        "type": "by_stock",
        "api": "fina_indicator",
        "path": "fina_indicator",
        "prefix": "fina_indicator_",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        **BY_STOCK_RUNTIME_CONFIG,
        "batch_per_trade_date_request": False,
        "batch_initial_code_chunk_size": 1000,
    },
    "fina_audit": {
        "type": "by_stock",
        "api": "fina_audit",
        "path": "fina_audit",
        "prefix": "fina_audit_",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        **BY_STOCK_RUNTIME_CONFIG,
        "batch_per_trade_date_request": False,
        "batch_initial_code_chunk_size": 1000,
    },
    "fina_mainbz": {
        "type": "by_stock",
        "api": "fina_mainbz",
        "path": "fina_mainbz",
        "prefix": "fina_mainbz_",
        "group": "financial",
        "date_col": "end_date",
        "root": "financial",
        "save_granularity": "year",
        "calendar_aligned": False,
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        **BY_STOCK_RUNTIME_CONFIG,
        "batch_per_trade_date_request": False,
        "batch_initial_code_chunk_size": 1000,
    },
    "disclosure_date": {
        "type": "by_stock",
        "api": "disclosure_date",
        "path": "disclosure_date",
        "prefix": "disclosure_date_",
        "group": "financial",
        "date_col": "ann_date",
        "root": "financial",
        "save_granularity": "year",
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        "batch_row_limit": 3000,
        "batch_initial_code_chunk_size": 3000,
        "expected_empty_ok": True,
        **BY_STOCK_RUNTIME_CONFIG,
    },
    "block_trade": {
        "type": "by_date",
        "api": "block_trade",
        "path": "block_trade",
        "prefix": "block_trade_",
        "force_by_date": True,
        "partition_by_year_dir": True,
        "retention_days": 400,
        "group": "block",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["price", "vol", "amount"],
    },
    "stk_shock": {
        "type": "by_date",
        "api": "stk_shock",
        "path": "stk_shock",
        "prefix": "stk_shock_",
        "force_by_date": True,
        "use_date_range_fetch": True,
        "fetch_full_years": True,
        "year_fetch_start_year": 2025,
        "save_granularity": "year",
        "partition_by_year_dir": True,
        "min_trade_date": "20250101",
        "group": "shock",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["name", "trade_market", "reason", "period"],
    },
    "margin": {
        "type": "by_stock",
        "api": "margin_detail",
        "path": "margin",
        "prefix": "margin_",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "health_recent_trade_days": 90,
        "group": "margin",
        "date_col": "trade_date",
        "root": "stock",
        "required_columns": ["rzye", "rqye"],
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        "batch_row_limit": 4000,
        "batch_initial_code_chunk_size": 500,
    },
    "stk_factor_pro": {
        "type": "standalone",
        "func": "update_stk_factor_pro",
        "group": "factor",
        "path": "stk_factor_pro",
        "prefix": "stk_factor_pro_",
        "date_col": "trade_date",
        "root": "stock",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "api_timeout_sec": 60,
        "date_request_retry_count": 3,
        "date_request_retry_sleep_sec": 1.0,
        "required_columns": ["open_qfq", "high_qfq", "low_qfq", "close_qfq"],
    },
    "stk_mins": {
        "type": "standalone",
        "func": "update_stk_mins",
        "group": "mins",
        "api": "stk_mins",
        "path": "分钟数据",
        "prefix": "",
        "date_col": "trade_time",
        "root": "stock",
        "save_granularity": "ymd_stock",
        "fetch_granularity": "minute",
        "calendar_aligned": False,
        "latest_trade_days_override": 1,
        "health_recent_trade_days": 5,
        "include_st_codes": True,
        "freq": "1min",
        "max_rows_per_call": 8000,
        "api_process_timeout_sec": 20,
        "progress_log_interval": 10,
        "active_code_log_interval": 0,
        "live_progress_include_code": False,
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "margin_detail": {
        "type": "standalone",
        "func": "update_margin_detail",
        "group": "margin",
        "path": "margin_detail",
        "prefix": "margin_detail_",
        "date_col": "trade_date",
        "root": "stock",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "required_columns": ["rzye", "rqye"],
        "nullable_columns": ["rqye"],
    },
    "pledge_stat": {
        "type": "standalone",
        "func": "update_pledge_stat",
        "group": "margin",
        "path": "pledge_stat",
        "prefix": "pledge_stat_",
        "api": "pledge_stat",
        "date_col": "end_date",
        "root": "stock",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "calendar_aligned": False,
        "latest_trade_days_override": 60,
        "health_recent_trade_days": 365,
        "required_columns": ["pledge_count", "pledge_ratio"],
    },
    "pledge_detail": {
        "type": "standalone",
        "func": "update_pledge_detail",
        "group": "margin",
        "path": "pledge_detail",
        "prefix": "pledge_detail_",
        "date_col": "ann_date",
        "root": "stock",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "calendar_aligned": False,
        "latest_trade_days_override": 60,
        "health_recent_trade_days": 365,
        "required_columns": ["holder_name", "pledge_amount", "start_date"],
        **BY_STOCK_RUNTIME_CONFIG,
    },
    "top10_holders": {
        "type": "standalone",
        "func": "update_top10_holders",
        "group": "holder",
        "path": "top10_holders",
        "prefix": "top10_holders_",
        "date_col": "end_date",
        "root": "stock",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "health_recent_trade_days": 365,
        "required_columns": ["holder_name"],
    },
    "top10_floatholders": {
        "type": "standalone",
        "func": "update_top10_floatholders",
        "group": "holder",
        "path": "top10_floatholders",
        "prefix": "top10_floatholders_",
        "date_col": "end_date",
        "root": "stock",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "health_recent_trade_days": 365,
        "required_columns": ["holder_name"],
    },
    "cyq_chips": {
        "type": "standalone",
        "func": "update_cyq_chips",
        "group": "factor",
        "path": "cyq_chips",
        "prefix": "cyq_chips_",
        "date_col": "trade_date",
        "root": "stock",
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        **BY_STOCK_BATCH_STOCK_POOL_CONFIG,
        "batch_row_limit": 2000,
        "batch_initial_code_chunk_size": 2000,
        "batch_size": 0,
        "estimated_rows_per_code": 100,
        "target_pages_per_batch": 1,
        "parallel_batches": 1,
        "batch_timeout_sec": 120,
        "retry_timeout_sec": 60,
        "progress_log_interval": 50,
        "chunk_days": 10,
        "required_columns": ["price", "percent"],
    },
    "cyq_perf": {
        "type": "standalone",
        "func": "update_cyq_perf",
        "group": "factor",
        "path": "cyq_perf",
        "prefix": "cyq_perf_",
        "date_col": "trade_date",
        "root": "stock",
        "use_pagination": True,
        "page_limit": 5000,
        "max_pages": 3,
        "required_columns": ["his_low", "his_high", "cost_5pct", "weight_avg"],
    },
    "weekly": {
        "type": "standalone",
        "func": "update_weekly",
        "group": "core",
        "path": "weekly",
        "prefix": "weekly_",
        "date_col": "trade_date",
        "root": "stock",
        "fetch_granularity": "weekly",
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "monthly": {
        "type": "standalone",
        "func": "update_monthly",
        "group": "core",
        "path": "monthly",
        "prefix": "monthly_",
        "date_col": "trade_date",
        "root": "stock",
        "fetch_granularity": "monthly",
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "index_basic": {
        "type": "standalone",
        "func": "update_index_basic",
        "group": "index",
        "path": "index_basic",
        "prefix": "index_basic_",
        "date_col": "trade_date",
        "root": "index",
        "fixed_file_name": "index_basic_all.csv",
        "required_columns": ["ts_code", "name", "market", "publisher"],
    },
    "index_daily": {
        "type": "standalone",
        "func": "update_index_daily",
        "group": "index",
        "path": "index_daily",
        "prefix": "index_daily_",
        "date_col": "trade_date",
        "root": "index",
        "code_param": "ts_code",
        "max_rows_per_call": 8000,
        "use_pagination": True,
        "page_limit": 8000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "live_progress_include_code": False,
        "health_recent_trade_days": 90,
        "fetch_granularity": "daily",
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "index_weekly": {
        "type": "standalone",
        "func": "update_index_weekly",
        "group": "index",
        "path": "index_weekly",
        "prefix": "index_weekly_",
        "date_col": "trade_date",
        "root": "index",
        "code_param": "ts_code",
        "max_rows_per_call": 1000,
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "live_progress_include_code": False,
        "health_recent_trade_days": 180,
        "fetch_granularity": "weekly",
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "index_monthly": {
        "type": "standalone",
        "func": "update_index_monthly",
        "group": "index",
        "path": "index_monthly",
        "prefix": "index_monthly_",
        "date_col": "trade_date",
        "root": "index",
        "code_param": "ts_code",
        "max_rows_per_call": 1000,
        "use_pagination": True,
        "page_limit": 2000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "save_granularity": "year_stock",
        "live_progress_include_code": False,
        "health_recent_trade_days": 365,
        "fetch_granularity": "monthly",
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "index_weight": {
        "type": "standalone",
        "func": "update_index_weight",
        "group": "index",
        "path": "index_weight",
        "prefix": "index_weight_",
        "date_col": "trade_date",
        "dedup_cols": ["index_code", "con_code", "trade_date"],
        "root": "index",
        "use_pagination": True,
        "page_limit": 5000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 180,
        "required_columns": ["weight"],
    },
    "index_global": {
        "type": "standalone",
        "func": "update_index_global",
        "group": "index",
        "path": "index_global",
        "prefix": "index_global_",
        "date_col": "trade_date",
        "root": "index",
        "fixed_file_name": "index_global_all.csv",
        "required_columns": ["ts_code", "name", "close"],
    },
    "index_classify": {
        "type": "standalone",
        "func": "update_index_classify",
        "group": "index",
        "path": "index_classify",
        "prefix": "index_classify_",
        "root": "index",
        "fixed_file_name": "index_classify_all.csv",
        "required_columns": ["index_code", "industry_name", "level"],
    },
    "index_member": {
        "type": "standalone",
        "func": "update_index_member",
        "group": "index",
        "path": "index_member",
        "prefix": "index_member_",
        "root": "index",
        "fixed_file_name": "index_member_all.csv",
        "required_columns": ["index_code", "con_code", "in_date"],
    },
    "sw_daily": {
        "type": "by_date",
        "api": "sw_daily",
        "path": "sw_daily",
        "prefix": "sw_daily_",
        "group": "index",
        "date_col": "trade_date",
        "root": "index",
        "force_by_date": True,
        "use_pagination": True,
        "page_limit": 8000,
        "max_pages": 4,
        "save_granularity": "year_stock",
        "partition_by_year_dir": True,
        "health_recent_trade_days": 90,
        "required_columns": ["open", "high", "low", "close", "vol", "amount"],
    },
    "rt_idx_k": {
        "type": "by_date",
        "api": "rt_idx_k",
        "path": "rt_idx_k",
        "prefix": "rt_idx_k_",
        "group": "index",
        "date_col": "trade_time",
        "root": "index",
        "use_pagination": True,
        "page_limit": 8000,
        "max_pages": 4,
        "partition_by_year_dir": True,
        "health_recent_trade_days": 30,
        "required_columns": ["name", "open", "high", "low", "close", "vol", "amount"],
    },
}


GROUPS = {
    "core": ["daily", "daily_basic", "moneyflow"],
    "limit": [
        "stk_nineturn",
        "limit_step",
        "limit_cpt_list",
        "limit_list_d",
        "limit_list_ths",
        "top_list",
        "top_inst",
        "kpl_list",
        "hm_detail",
        "hm_list",
    ],
    "moneyflow": [
        "moneyflow",
        "moneyflow_ths",
        "moneyflow_hsgt",
        "moneyflow_ind_ths",
        "moneyflow_cnt_ths",
        "moneyflow_mkt_dc",
    ],
    "repurchase": ["repurchase"],
    "block": ["block_trade"],
    "shock": ["stk_shock"],
    "holder": ["top10_holders", "top10_floatholders"],
    "factor": ["cyq_chips", "cyq_perf", "stk_factor_pro"],
    "mins": ["stk_mins"],
    "theme": ["dc_concept", "kpl_concept_cons", "dc_concept_cons", "ths_index", "ths_member", "ths_daily", "dc_daily", "dc_index", "dc_member"],
    "financial": [
        "forecast",
        "express",
        "fina_mainbz",
        "disclosure_date",
        "income",
        "balancesheet",
        "cashflow",
        "fina_indicator",
    ],
    "index": [
        "index_basic",
        "index_daily",
        "index_weekly",
        "index_monthly",
        "index_weight",
        "index_global",
        "index_classify",
        "index_member",
        "sw_daily",
        "rt_idx_k",
    ],
}


AUTO_FILL_STOCK_BY_DATE_NAMES = [
    "daily",
    "daily_basic",
    "moneyflow",
    "moneyflow_ths",
    "limit_list_d",
    "top_list",
    "top_inst",
    "block_trade",
    "repurchase",
    "stk_shock",
    "stk_auction_o",
    "stk_auction_c",
    "cyq_perf",
    "stk_factor_pro",

    "dc_concept",
    "ths_index",
    "kpl_list",
    "kpl_concept_cons",
    "ths_member",
    "ths_daily",
    "dc_daily",
    "dc_index",
    "dc_member",
    "hm_list",
    "forecast",
]

AUTO_FILL_STOCK_BY_STOCK_NAMES = [
    "margin_detail",
    "pledge_stat",
    "margin",
    "cyq_chips",
    "express",
    "disclosure_date",
    "stk_mins",
    "income",
    "balancesheet",
    "cashflow",
    "fina_indicator",
    "fina_mainbz",
]

AUTO_FILL_INDEX_BY_DATE_NAMES = [
    "sw_daily",
    "index_weight",
]

AUTO_FILL_INDEX_BY_INDEX_NAMES = ["index_daily", "index_weekly", "index_monthly"]


def _apply_autofill_runtime_defaults(name, config):
    """Apply runtime defaults to an interface config."""
    runtime_config = deepcopy(config)
    runtime_config.setdefault("health_scan_log_interval", 1000)

    if runtime_config.get("type") == "by_stock" or name in AUTO_FILL_STOCK_BY_STOCK_NAMES:
        runtime_config.setdefault("resume_code_state", True)
        runtime_config.setdefault("api_process_timeout_sec", 20)
        runtime_config.setdefault("progress_log_interval", 50)
        runtime_config.setdefault("active_code_log_interval", 0)
        runtime_config.setdefault("live_progress_include_code", False)
    if name == "cyq_chips":
        runtime_config["batch_size"] = int(runtime_config.get("batch_size") or 0)
        runtime_config["parallel_batches"] = int(runtime_config.get("parallel_batches") or 1)
        runtime_config["batch_timeout_sec"] = min(int(runtime_config.get("batch_timeout_sec") or 120), 120)
        runtime_config["retry_timeout_sec"] = min(int(runtime_config.get("retry_timeout_sec") or 60), 60)
        runtime_config.setdefault("progress_log_interval", 50)

    return runtime_config


def _subset(names):
    return {
        name: _apply_autofill_runtime_defaults(name, INTERFACE_CONFIG[name])
        for name in names
    }


def build_auto_fill_registry():
    """Return the autofill config split by stock/index and fetch mode."""
    return {
        "stock": {
            "by_date": _subset(AUTO_FILL_STOCK_BY_DATE_NAMES),
            "by_stock": _subset(AUTO_FILL_STOCK_BY_STOCK_NAMES),
        },
        "index": {
            "by_date": _subset(AUTO_FILL_INDEX_BY_DATE_NAMES),
            "by_index": _subset(AUTO_FILL_INDEX_BY_INDEX_NAMES),
        },
    }


def iter_auto_fill_interfaces(registry=None):
    """Yield (domain, bucket_name, interface_name, config) tuples."""
    registry = registry or build_auto_fill_registry()
    for domain, buckets in registry.items():
        for bucket_name, interfaces in buckets.items():
            for name, config in interfaces.items():
                yield domain, bucket_name, name, config


def list_auto_fill_interface_names(registry=None):
    """Return canonical autofill interface names in workflow order."""
    return [name for _, _, name, _ in iter_auto_fill_interfaces(registry)]
